version: '3.3'
services:
  php-apache-environment:
    container_name: c-001-php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - ../php/src:/var/www/html/
    ports:
      - '8011:80'
    networks:
      - default

  db:
#    container_name: c-001-db
    image: mysql:5.7
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    container_name: c-001-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - 'db'
    links:
      - db:db
    networks:
      - default

volumes:
  my-db:
  persistent:
