services:
  php-8-0:
    build: ./php-app
    container_name: exp_php_8_0_app
    volumes:
      - ./php-app:/var/www
    expose:
      - "9000"

  nginx-for-php-8-0:
    image: nginx:latest
    container_name: exp_php_8_0_app_nginx_server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php-app/public:/var/www/public
    ports:
      - "8080:80"
    depends_on:
      - php-8-0